repos:
  - repo: local
    hooks:
      - id: typescript-check
        name: TypeScript compilation check
        entry: npx tsc -p tsconfig.json --noEmit
        language: system
        types: [typescript, tsx]
        pass_filenames: false
        
      - id: eslint
        name: ESLint
        entry: npx eslint . --ext .js,.jsx,.ts,.tsx
        language: system
        types: [javascript, typescript, jsx, tsx]
        pass_filenames: false
        
      - id: jest-tests
        name: Jest tests
        entry: pnpm test --silent
        language: system
        types: [javascript, typescript, jsx, tsx]
        pass_filenames: false
        
      - id: prettier
        name: Prettier formatting
        entry: pnpm format:check
        language: system
        types: [javascript, typescript, jsx, tsx, json, yaml, markdown]
        pass_filenames: false